#!/bin/bash
mkdir -p /proc /sys /tmp /dev /etc /root /run /boot
mount -t proc none /proc
mount -t devtmpfs none /dev
mount -t sysfs none /sys
mount -t efivarfs none /sys/firmware/efi/efivars
mount -t securityfs none /sys/kernel/security

echo "Hello, initrd" > /dev/console
echo "Hello, initrd (ttyprintk)" > /dev/ttyprintk
exec < /dev/console >/dev/console 2>/dev/console

export PS1='\w# '
if [ -x /bin/setsid ]; then
	exec /bin/setsid -c /bin/bash
fi

# fall back to a normal shell with no job control
exec /bin/bash
