#!/bin/bash
die() { echo "$@" >&2 ; exit 1 ; }

FILE="$1"
if [ -z "$FILE" ]; then
	die "Usage: chainload /path/to/executable.efi"
fi
if [ ! -r "$FILE" ]; then
	die "chainload: $FILE not readable"
fi

DIR="$(dirname $0)"
CHAINLOAD_BIN="$DIR/chainload.bin"

if [ ! -r "$CHAINLOAD_BIN" ]; then
	die "chainload: resume code $CHAINLOAD_BIN does not exist"
fi

dd \
	if=/dev/mem \
	of=/tmp/context.bin \
	bs=1024 \
	count=1 \
|| die "chainload: unable to copy UEFI context from /dev/mem"

xxd -g8 /tmp/context.bin | grep '1..:'

kexec-load \
        -e 0x40000000 \
        0x0=/tmp/context.bin \
        0x40000000="$CHAINLOAD_BIN" \
        0x40100000="$FILE" \
&& kexec -e

die "chainload: kexec failed?"
